test test job

diff --git a/.github/workflows/end2end.yaml b/.github/workflows/end2end.yaml
--- a/.github/workflows/end2end.yaml
+++ b/.github/workflows/end2end.yaml
@@ -43,13 +43,12 @@ jobs:
         kubectl get pods
     - name: Check Canary 00
       run: |
-        kubectl port-forward service/canary-00-canary-bot-api 18080:8080 &
-        curl -v -H 'Authorization: Bearer 12345678' -H 'Content-Type: application/json' 127.0.0.1:18080/api/v1/samples 
-    - name: Check Canary 01
-      run: |
-        kubectl port-forward service/canary-01-canary-bot-api 28080:8080 &
-        curl -v -H 'Authorization: Bearer 12345678' -H 'Content-Type: application/json' 127.0.0.1:28080/api/v1/samples 
-    #- name: Check Canary 01
-    #  run: |
-    #    SERVICE=$(kubectl get services canary-01-canary-bot-api -o jsonpath={.spec.clusterIP})
-    #    curl -v -H 'Authorization: Bearer 12345678' -H 'Content-Type: application/json' ${SERVICE}:8080/api/v1/samples 
+        kubectl create job curl --image=mtr.devops.telekom.de/mcsps/curl:7.65.3 -- curl -f -v -H 'Authorization: Bearer 12345678' -H 'Content-Type: application/json'  http://canary-00-canary-bot-api:8080/api/v1/samples
+        STATUS=$(kubectl get job curl -o jsonpath={.status.succeeded})
+        if [ $STATUS  -ne  1 ]
+        then
+          echo "Job failed"
+          kubectl logs -ljob-name=curl
+          kubectl delete job curl
+          exit 1
+        fi
